# Generated by Django 5.0.6 on 2024-05-31 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='no_image.jpg', upload_to='images/'),
        ),
    ]
