# Generated by Django 5.0.6 on 2024-05-31 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='images/no_image.jpg', upload_to='images/'),
        ),
    ]
